sudo: required
services:
  - docker

before_install:
  - docker build -t wilkinsleung/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wilkinsleung/react-test npm run test

after_success:
  - docker build -t wilkinsleung/multi-client ./client
  - docker build -t wilkinsleung/multi-nginx  ./nginx
  - docker build -t wilkinsleung/multi-server ./server
  - docker build -t wilkinsleung/multi-worker ./worker
  # Login to docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  # Take those image and push them to docker hub
  - docker push wilkinsleung/multi-client
  - docker push wilkinsleung/multi-nginx
  - docker push wilkinsleung/multi-server
  - docker push wilkinsleung/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: fibCalc-multi-docker
  env: FibcalcMultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-976392945067
  bucket_path: fibCalc-multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY